name: Build Rules JSON

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Process TS Files
        run: node build-rules.js

      - name: Commit and Push
        id: commit_step
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist/rules.json
          # 检查是否有更新，并记录结果
          if git diff --quiet && git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "chore: update rules.json"
            git push
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Purge jsDelivr Cache
        if: steps.commit_step.outputs.changed == 'true'
        run: |
          BASE_URL="https://purge.jsdelivr.net/gh/${{ github.repository }}@main/dist"
          echo "正在刷新 rules.json..."
          curl -i "${BASE_URL}/rules.json"
          echo -e "\n正在刷新 config.txt..."
          curl -i "${BASE_URL}/config.txt"
